name: ci-cd-test

on:
  push:
    branches: 
      - master
    tags:
      - deploy**

jobs:
  ci-cd:
    runs-on: ubuntu-latest
    name: Build & Deploy

    steps:
      - uses: actions/checkout@v2